* Orgzly II

Orgzly II is a continuation of the original Orgzly project. It is an outliner for taking notes and managing to-do lists. It natively supports the OrgMode syntax.

With Orgzly, you can keep notebooks stored in plain-text and have them synchronized
with a directory on your mobile device or an SD card, or a WebDAV server. Synchronizing with a local directory allows you to use any file synchronization service (e.g. Syncthing, Nextcloud, Dropbox) or a source code repository to keep your notes in sync across multiple devices.

Notebooks are saved in /Org mode/'s file format. “Org mode is for
keeping notes, maintaining TODO lists, planning projects, and
authoring documents with a fast and effective plain-text system.” See
http://orgmode.org for more information.

* Why Orgzly II?

The project aims to keep the application alive and up-to-date with the current Android requirements and provide reliable and dependable application support for existing users.

* Support

- See the detailed [[https://github.com/orgzly/documentation][End-user documentation]]

* Install

The app can be installed and kept up-to-date by using Obtainium and referencing this repository.

* Development

If you don't use Android Studio and wish to build and test the app from command line, the standard set of Gradle tasks is available. For example:

- ~./gradlew build~ builds the project and generates APK files
- ~./gradlew connectedAndroidTest~ runs instrumented unit tests

Make sure you [[https://developer.android.com/training/testing/espresso/setup][turn off animations]] for the device you're testing on.

* License

The project is licensed under the [[LICENSE][GNU General Public License version 3 (or newer)]].
