# You should copy this file to "keystore.properties" which is required for release signing.
#
# storeFile=path/to/your/keystore.jks
# storePassword=your_keystore_password
# keyAlias=your_key_alias
# keyPassword=your_key_password
